# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "_name"
    config.vm.hostname = "nu"

    config.vm.provider "VirtualBox" do |vb|
      # Display the VirtualBox GUI when booting the machine
      vb.gui = true
      # Customize the amount of memory on the VM:
      vb.memory = "2048"
      vb.cpus = 2
    end
    config.vm.provision "shell", privileged: "true", inline: <<-'SHELL'
        apt-get upgrade -y
    SHELL
  end